version: "3"
services:
  linux_with_nvm:
    build: .
    stdin_open: true
    tty: true
    depends_on:
    - mongodb
    ports:
    - 3000:3000
    volumes:
    - .:/usr/app
  mongodb:
    image: "mongo:3.0-wheezy"
    environment:
    - MONGO_DATA_DIR=/usr/data
    - MONGO_LOG_DIR=/dev/null
    ports:
    - 27017:27017
    volumes:
    - my-vol:/usr/data
    command: mongod
volumes:
  my-vol: {}
